### ISSUE TITLE
Add permission support

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-drupal-symfony2-bridge#10]
```
search.reindex_confirm:
  path: '/admin/config/search/pages/reindex'
  requirements:
    _permission: 'administer search'
```

```
administer search:
  title: 'Administer search'
```
