### ISSUE TITLE
Add linemaker, indexer and completion for entity forms

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-drupal-symfony2-bridge#11]
```
search.add_type:
  path: '/admin/config/search/pages/add/{search_plugin_id}'
  defaults:
    _entity_form: 'search_page.add'
```

```
 * @ConfigEntityType(
 *   id = "search_page",
```
