### ISSUE TITLE
Completion for non default Symfony route keys

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-drupal-symfony2-bridge#12]
```
entity.search_page.edit_form:
  path: '/admin/config/search/pages/manage/{search_page}'
  defaults:
    _entity_form: 'search_page.edit'
    _title_callback: '\Drupal\search\Controller\SearchController::editTitle'
    op: 'enable'
```

```
  requirements:
    _entity_access: 'search_page.update'
```
