### ISSUE TITLE
Key completion for yaml menus

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-drupal-symfony2-bridge#13]
```
search.view:
  title: Search
  route_name: search.view
  enabled: 0
entity.search_page.collection:
  title: 'Search pages'
  parent: system.admin_config_search
  description: 'Configure search pages and search indexing options.'
  route_name: entity.search_page.collection
  weight: -10
```
