### ISSUE TITLE
Provide references and completion for controller

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-drupal-symfony2-bridge#39]
Provide a better controller class detection
--------

1. We have the following controller:

```php
<?php
namespace Drupal\hello_world\Controller;
use Drupal\Core\Controller\ControllerBase;
class HelloController extends ControllerBase{
    public function content()
    {
        return array(
            '#type' => 'markup',
            '#markup' => $this->t('Hello World'),
        );
    }
}
```

```yaml
hello_world.content:
  path: '/hello'
  defaults:
    _controller: '<caret>'
    _title: 'Hello World'
  requirements:
    _permission: 'access content'
```
There will be no completion at the caret. After insertion of \Drupal\hello_world\Controller\HelloController it won't be possible to navigate to the class.

As a first step we can provide completion and make references in all string values.

https://youtrack.jetbrains.com/issue/WI-38073
