### ISSUE TITLE
Add controller completion

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-drupal-symfony2-bridge#6]
```
history.get_last_node_view:
  path: '/history/get_node_read_timestamps'
  defaults:
    _controller: '\Drupal\history\Controller\HistoryController::getNodeReadTimestamps'
```
