### ISSUE TITLE
Support task based routes

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-drupal-symfony2-bridge#8]
```
entity.aggregator_feed.canonical:
  route_name: entity.aggregator_feed.canonical
  base_route: entity.aggregator_feed.canonical
  title: View
```
