### ISSUE TITLE
Support configuration

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-drupal-symfony2-bridge#9]
```
Drupal\Core\Config\ConfigFactoryInterface::get
core/modules/system/config/schema/system.schema.yml
```

```
system.diff:
  type: config_object
  label: 'Diff settings'
  mapping:
    context:
      type: mapping
      label: 'Context'
      mapping:
        lines_leading:
          type: integer
          label: 'Number of leading lines in a diff'
        lines_trailing:
          type: integer
          label: 'Number of trailing lines in a diff'
```

```
    $config = $config_factory->get('system.diff');
    $this->leading_context_lines = $config->get('context.lines_leading');
    $this->trailing_context_lines = $config->get('context.lines_trailing');
```
